local manager = require("scripts.manager")

function init(self)
	msg.post("@render:", "use_camera_projection")
	msg.post("@render:", "clear_color", { color = vmath.vector4(198 / 255, 189 / 255, 22 / 255, 0) })

	profiler.enable_ui(false)
	profiler.set_ui_view_mode(profiler.VIEW_MODE_MINIMIZED)

	local color_green = vmath.vector4(0, 1, 0, 1)

	manager.init()
end

function on_message(self, message_id, message, sender)
	manager.message(self, message_id, message, sender)
end
